// Conformance check of the local emulation against the real supabase-js client.
import { createClient } from "@supabase/supabase-js";
import { startStack } from "./stack.mjs";
const secret = "selftest-" + Math.random();
const s = await startStack({ port: 54399, jwtSecret: secret, quiet: true });
let bad = 0;
const ok = (n, c, d = "") => { console.log(`${c ? "ok  " : "FAIL"} ${n} ${c ? "" : d}`); if (!c) bad++; };
const mk = () => createClient(s.url, s.anonKey, { auth: { persistSession: false } });
const a = mk(), b = mk(), anon = mk();
let r = await a.auth.signUp({ email: "a@x.test", password: "secret1", options: { data: { full_name: "Alice" } } });
ok("signup returns a session", !!r.data.session, JSON.stringify(r.error));
r = await b.auth.signUp({ email: "b@x.test", password: "secret1", options: { data: { full_name: "Bob" } } });
const A = (await a.auth.getUser()).data.user, B = (await b.auth.getUser()).data.user;
ok("getUser works", A?.email === "a@x.test" && B?.email === "b@x.test");
const bad1 = await mk().auth.signInWithPassword({ email: "a@x.test", password: "wrong" });
ok("bad password rejected", !!bad1.error);
const prof = await a.from("profiles").select("full_name").eq("id", A.id).single();
ok("profile created by trigger from signup metadata", prof.data?.full_name === "Alice", JSON.stringify(prof));
const f = await a.from("farmers").insert({ owner_id: A.id, name: "F" }).select().single();
ok("insert+select().single()", !f.error && f.data.name === "F", JSON.stringify(f.error));
const p = await a.from("plots").insert({ owner_id: A.id, farmer_id: f.data.id, name: "P", crop: "Rice", area: 1, boundary: { type: "Polygon", coordinates: [[[1, 1], [2, 1], [2, 2], [1, 1]]] } }).select("*, farmers(name)").single();
ok("insert plot with embedded parent", !p.error && p.data.farmers?.name === "F" && p.data.boundary.type === "Polygon", JSON.stringify(p.error ?? p.data));
await s.exec("insert into public.digital_twins (plot_id, analysis_date, crop_health_score) values ($1, now(), 70)", [p.data.id]);
const l = await a.from("plots").select("*, digital_twins(*), farmers(name)").eq("owner_id", A.id).order("created_at", { ascending: false });
ok("select with child + parent embeds", !l.error && l.data.length === 1 && l.data[0].digital_twins.length === 1, JSON.stringify(l.error ?? l.data));
const cross = await b.from("plots").select("*").eq("id", p.data.id);
ok("B cannot read A's plot (RLS)", !cross.error && cross.data.length === 0);
const upd = await b.from("plots").update({ name: "pwn" }).eq("id", p.data.id).select();
ok("B cannot update A's plot", !upd.error && upd.data.length === 0);
const steal = await b.from("soil_reports").insert({ owner_id: B.id, plot_id: p.data.id, nitrogen_kg_ha: 1, phosphorus_kg_ha: 1, potassium_kg_ha: 1, organic_carbon_percent: 1, ph: 7 });
ok("B cannot attach a report to A's plot", !!steal.error, "inserted!");
const none = await anon.from("plots").select("*");
ok("anon sees nothing", !none.error && none.data.length === 0);
const sr = await a.from("soil_reports").select("*").eq("plot_id", p.data.id).order("created_at", { ascending: false }).limit(1).maybeSingle();
ok("maybeSingle on empty result", !sr.error && sr.data === null, JSON.stringify(sr));
const ins = await a.from("plots").select("id").in("id", [p.data.id]);
ok("in() filter", ins.data?.length === 1);
const forged = createClient(s.url, s.anonKey, { auth: { persistSession: false }, global: { headers: { Authorization: "Bearer not-a-jwt" } } });
const fr = await forged.from("plots").select("*");
ok("forged bearer rejected", !!fr.error);
await a.auth.signOut();
await s.close();
process.exit(bad ? 1 : 0);
